- name: Install the latest version of Apache
  ansible.builtin.dnf:
    name: httpd
    state: latest

- name: Make sure a service unit is running
  ansible.builtin.systemd_service:
    state: started
    name: httpd
