- name: Create WordPress image
  hosts: all
  remote_user: ec2-user
  become: true
  become_method: sudo
  roles:
    - disable-selinux
    - upgrade-all-packages
    - install-development-tools
    - install-httpd
    - install-php
    - install-wordpress
