- name: Download WordPress
  ansible.builtin.get_url:
    url: http://ja.wordpress.org/latest-ja.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Unarchive wordpress.tar.gz
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp/
    remote_src: true

- name: Copy wordpress to DocumentRoot
  ansible.builtin.copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    owner: apache
    group: apache
    remote_src: true
